[package]
name = "rcubes"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
default = ["console_error_panic_hook"]

[dependencies]
js-sys = "0.3.37"
wasm-bindgen = "0.2.60"
wasm-bindgen-futures = "0.4.10"
nalgebra-glm = "0.7.0"
gltf = "0.15.2"
console_error_panic_hook = { version = "0.1.1", optional = true }
wee_alloc = { version = "0.4.2", optional = true }
serde = { version = "1.0.80", features = ["derive"] }
serde_derive = "^1.0.59"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'EventTarget',
  'EventListener',
  'HtmlElement',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'Window',
  'console',
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'XmlHttpRequest'
]

[profile.release]
debug = true